// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */

// @ts-expect-error - generated JS file without type declarations

export const functions = {
	
};
